# Generated by Django 2.2.16 on 2022-03-23 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='personnel',
            fields=[
                ('matricule', models.IntegerField(max_length=20)),
                ('matr_corps', models.IntegerField(max_length=20)),
                ('code_grd', models.IntegerField(max_length=11)),
                ('IU', models.IntegerField(max_length=15)),
                ('CIN', models.IntegerField(max_length=8, primary_key=True, serialize=False)),
                ('date_cin', models.DateField()),
                ('date_nomination', models.DateField()),
                ('Prenom', models.CharField(max_length=40)),
                ('NOM', models.CharField(max_length=40)),
                ('Prenom_pere', models.CharField(max_length=40)),
                ('Prenom_mere', models.CharField(max_length=40)),
                ('Situation_familial', models.CharField(max_length=15)),
                ('date_naissance', models.DateField()),
                ('Lieu_naiss', models.CharField(max_length=40)),
                ('cd_spec', models.IntegerField(max_length=11)),
                ('code_qualification', models.IntegerField(max_length=10)),
                ('date_entr_serv', models.DateField()),
                ('date_deb_contrat', models.DateField()),
                ('date_fin_contrat', models.DateField()),
                ('Adresse', models.TextField()),
                ('Telephone', models.IntegerField(max_length=8)),
                ('Telephone2', models.IntegerField(max_length=8)),
                ('cd_unite', models.IntegerField(max_length=11)),
                ('obsrv', models.TextField()),
                ('date_fin_CIM', models.DateField()),
                ('CIM', models.IntegerField(max_length=8)),
                ('taille', models.IntegerField(max_length=8)),
                ('poids', models.IntegerField(max_length=8)),
                ('sexe', models.CharField(max_length=10)),
                ('pointure', models.IntegerField(max_length=8)),
                ('gp_sanguin', models.CharField(max_length=10)),
                ('etat_civil', models.CharField(max_length=20)),
                ('img', models.IntegerField()),
                ('code_service', models.IntegerField(max_length=20)),
                ('code_fonction', models.IntegerField(max_length=20)),
                ('prenom_partenaire', models.CharField(max_length=20)),
                ('prenom_grandpere', models.CharField(max_length=20)),
                ('nbr_enfant', models.IntegerField(verbose_name=2)),
                ('armee', models.CharField(max_length=20)),
                ('prenomf', models.CharField(max_length=20)),
                ('nomf', models.CharField(max_length=20)),
                ('arme', models.CharField(max_length=20)),
                ('etat', models.CharField(max_length=20)),
                ('groupe', models.CharField(max_length=20)),
                ('office', models.CharField(max_length=20)),
                ('situation', models.CharField(max_length=20)),
                ('niv_int', models.CharField(max_length=30)),
                ('origine_recrutement', models.CharField(max_length=30)),
                ('date_diplome', models.DateField()),
                ('date_entr_hopi', models.DateField()),
                ('date_specialite', models.DateField()),
                ('date_fonction', models.DateField()),
                ('date_qualif_militaire', models.DateField()),
            ],
        ),
    ]
