# Generated by Django 2.2.16 on 2022-03-24 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='matricule1',
            field=models.IntegerField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
