# Generated by Django 2.2.16 on 2022-03-24 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0002_personnel_matricule1'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personnel',
            options={'managed': False},
        ),
    ]
