# Generated by Django 2.2.16 on 2022-03-31 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0003_auto_20220324_1144'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='personnel',
            table='personnel',
        ),
    ]
