# Generated by Django 4.1.5 on 2024-07-17 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0004_rename_average_weight_tank_tank_average_weight_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tank',
            name='newfield',
        ),
    ]
