# Generated by Django 2.2.16 on 2022-04-21 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0005_archive'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('code_grade', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('libelle_grade', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'grade',
                'managed': False,
            },
        ),
    ]
