# Generated by Django 4.1.5 on 2024-07-18 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0005_remove_tank_newfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='FishTransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_fish', models.IntegerField()),
                ('average_weight', models.FloatField()),
                ('date_of_transfer', models.DateTimeField(auto_now_add=True)),
                ('tank_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_out', to='personnel.tank')),
                ('tank_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_in', to='personnel.tank')),
            ],
            options={
                'db_table': 'FishTransfer',
            },
        ),
    ]
