# Generated by Django 2.2.16 on 2022-04-24 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0006_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arme',
            fields=[
                ('code_arme', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('libelle_arme', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'arme',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bureau',
            fields=[
                ('code_bureau', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('libelle_bureau', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'bureau',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fonction',
            fields=[
                ('code_fonction', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('libelle_fonction', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'fonction',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Qualification_mil',
            fields=[
                ('code_qualification_mil', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('libelle_qualification_mil', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'qualification_mil',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('code_region', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('libelle_sregion', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'region',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('code_service', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('libelle_service', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'service',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Situation',
            fields=[
                ('code_situation', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('libelle_situation', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'situation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Specialite',
            fields=[
                ('code_specialite', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('libelle_specialite', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'specialite',
                'managed': False,
            },
        ),
    ]
