# Generated by Django 3.2.7 on 2022-04-27 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0007_auto_20220427_1409'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
