# Generated by Django 3.2.7 on 2022-04-27 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0010_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='taher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=20, unique=True)),
                ('matr_corps', models.CharField(blank=True, max_length=20, null=True)),
                ('hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
