# Generated by Django 3.2.7 on 2022-04-27 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0012_alter_taher_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='taher',
        ),
    ]
