# Generated by Django 3.2.7 on 2022-04-27 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0014_taher'),
    ]

    operations = [
        migrations.CreateModel(
            name='mouhamed',
            fields=[
                ('matricule', models.IntegerField(max_length=20, primary_key=True, serialize=False)),
                ('matr_corps', models.CharField(blank=True, max_length=20, null=True)),
                ('kkkk', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
