# Generated by Django 3.2.7 on 2022-04-27 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0015_mouhamed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taher',
            options={},
        ),
    ]
