from rest_framework import serializers
from personnel.models import Personnel



class personnelSerializer(serializers.ModelSerializer):
    class Meta:
        model = Personnel
        fields = ('matricule',
                'matr_corps',
                'cd_grd',
                'grade',
                'iu',
                'cin',
                'dtecin',
                'date_nomination',
                'prenom',
                'nom',
                'prenom_pere',
                'prenom_mere',
                'situation_familiale',
                'date_naissance',
                'lieu_naiss',
                'cd_spec',
                'specialite',
                'qualification',
                'date_entr_serv',
                'date_deb_contrat',
                'date_fin_contrat',
                'adresse',
                'telephone',
                'telephone2',
                'base',
                'unite',
                'position',
                'obsrv',
                'idunique',
                'passp1',
                'passp2',
                'famille',
                'secteur',
                'categ',
                'dtefincim',
                'cim',
                'taille',
                'poids',
                'sexe',
                'pointure',
                'gpsanguin',
                'etatcivil',
                'img',
                'service',
                'code_fonction',
                'prenom_partenaire',
                'prenom_grandpere',
                'nbr_enfant',
                'armee',
                'prenomf',
                'nomf',
                'arme',
                'etat',
                'fonction',
                'groupe',
                'office',
                'situation',
                'niv_intel',
                'origine_recrutement',
                'date_diplome',
                'qualification_militaire',
                'date_entr_hopi',
                'date_specialite',
                'date_fonction',
                'date_qualif_militaire',

        )

